Add some tests for Session module
Need to solve the problem with the validation error test given the following at a later time:

```
TypeError: argument 'line_errors': 'ModelMetaclass' object cannot be converted to 'Sequence'
```